"TOTAL_TIMESTEPS": 8e7
"NUM_ENVS":  512 
"NUM_STEPS":  32 
"HIDDEN_SIZE": 512
"NUM_LAYERS": 2
"NORM_TYPE": "layer_norm"
"NORM_INPUT": False
"EPS_START": 1
"EPS_FINISH": 0.1
"EPS_DECAY": 0.1
"MAX_GRAD_NORM": 10
"NUM_MINIBATCHES": 4
"NUM_EPOCHS": 4
"LR":   0.0001
"LR_DECAY": "LINEAR"
"LAMBDA": 0.75
"GAMMA": 0.99
"LR_DECAY_TIME": 1.
"LR_DECAY_FINISH": 0.0001

# env
"ENV_NAME": "communication"
"ENV_KWARGS": 
  num_classes: 4 
  max_games: 16
  reveal_class: True
  reveal_correct: False 
  force_action: False
  blank_rew: 0.
  incorrect_rew: -1
"REW_SHAPING_HORIZON":  8e6 


# evaluate
"TEST_DURING_TRAINING": True
"TEST_INTERVAL": 0.01 
"TEST_NUM_STEPS": 12
"TEST_NUM_ENVS": 25 

