"ENV_NAME": "overcooked_v2"
"ENV_KWARGS": 
  "layout" : "test_time_simple" # wide_cramped_room_v2, test_time_simple
  "agent_view_size": 2
  "negative_rewards": True
  "sample_recipe_on_delivery": True
  "random_agent_positions": True

"POP_SIZE" : 10
"FCP_CHECKPOINTS": [
            "baseline_seed_0_step_225.msgpack", # 50%
            "baseline_seed_1_step_225.msgpack", # 50%
            "baseline_seed_2_step_315.msgpack", # 60%
            "baseline_seed_3_step_315.msgpack", # 60%
            "baseline_seed_4_step_360.msgpack", # 70%
            "baseline_seed_5_step_360.msgpack", # 70%
            "baseline_seed_6_step_360.msgpack", # 70%
            "baseline_seed_7_step_450.msgpack", # 100%
            "baseline_seed_8_step_450.msgpack",  # 100%
            "baseline_seed_9_step_450.msgpack",  # 100%
        ]
"USE_TOM" : True
"PARAM_MODE": "shared"
"STOP_GRAD_OTHER": True
"LR": 0.00025
"ANNEAL_LR": True
"LR_WARMUP": 0.05

"NUM_ENVS": 256
"NUM_STEPS": 256
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 64

"TOTAL_TIMESTEPS": 3e7
"REW_SHAPING_HORIZON": 1.5e7

"FC_DIM_SIZE": 128
"GRU_HIDDEN_DIM": 128

"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"SCALE_CLIP_EPS": False
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.25
"ACTIVATION": "relu"
"SEED": 0
"NUM_SEEDS": 5

"ENTITY": "maytusp"
"PROJECT": "like-me-tom-overcookedv2"
"WANDB_MODE" : "online"
